# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rails_react_foodie_development
  username: chiageng
  password: Chiageng1898@
test:
  <<: *default
  database: rails_react_foodie_test
production:
  <<: *default
  database: rails_react_foodie_production
  username: rails_react_foodie
  password: <%= ENV['RAILS_REACT_FOODIE_DATABASE_PASSWORD'] %>
